export const GET_AUTH_TOKEN = "GET_AUTH_TOKEN";
export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAILURE = 'AUTH_FAILURE'

export const GET_MOVIE_LIST = 'GET_MOVIE_LIST'
export const MOVIE_LIST_SUCCESS = 'MOVIE_LIST_SUCCESS'
export const MOVIE_LIST_FAILURE = 'MOVIE_LIST_FAILURE'

export const FETCH_GENRE_LIST = 'FETCH_GENRE_LIST'
export const FETCH_GENRE_SUCCESS = 'FETCH_GENRE_SUCCESS'
export const FETCH_GENRE_FAILURE = 'FETCH_GENRE_FAILURE'

export const FETCH_AIR_NOW_LIST = 'FETCH_AIR_NOW_LIST'
export const FETCH_AIR_NOW_SUCCESS = 'FETCH_AIR_NOW_SUCCESS'
export const FETCH_AIR_NOW_FAILURE = 'FETCH_AIR_NOW_FAILURE'