export const GET_AUTH_TOKEN = "GET_AUTH_TOKEN";
export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAILURE = 'AUTH_FAILURE'

export const GET_MOVIE_LIST = 'GET_MOVIE_LIST'
export const MOVIE_LIST_SUCCESS = 'MOVIE_LIST_SUCCESS'
export const MOVIE_LIST_FAILURE = 'MOVIE_LIST_FAILURE'